### ISSUE TITLE
Getting `unreachable` opcode error when calling into jsvm.testnet

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-sdk-js#22]
I'm trying to make a call into `jsvm.testnet` on the example status message contract and getting this error:
```
❯ near call jsvm.testnet call_js_contract \
    --accountId instanton.testnet \
    --args $(node near-sdk-js/encode_call.js instanton.testnet init '') \
    --base64


Scheduling a call: jsvm.testnet.call_js_contract(aW5zdGFudG9uLnRlc3RuZXQAaW5pdAA=)
Doing account.functionCall()
Receipt: 3F6XonmvVDs8mFeGXxVcn1W17PnH416WD8uYgmt7j5Hu
        Failure [jsvm.testnet]: Error: {"index":0,"kind":{"ExecutionError":"WebAssembly trap: An `unreachable` opcode was executed."}}
ServerTransactionError: {"index":0,"kind":{"ExecutionError":"WebAssembly trap: An `unreachable` opcode was executed."}}
    at Object.parseResultError (/Users/tensor/space/near-cli-js/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/Users/tensor/space/near-cli-js/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async scheduleFunctionCall (/Users/tensor/space/near-cli-js/commands/call.js:57:38)
    at async Object.handler (/Users/tensor/space/near-cli-js/utils/exit-on-error.js:52:9) {
  type: 'FunctionCallError',
  context: undefined,
  index: 0,
  kind: {
    ExecutionError: 'WebAssembly trap: An `unreachable` opcode was executed.'
  },
  transaction_outcome: {
    block_hash: '6Fboj3nZsE6NNLNYWXDJAC8qkLGUfFXpX4r6ZRaTL6sp',
    id: 'A4nZ5XtcUptfppbggrJkKrpEmNb69KayQRZWQvRkimTs',
    outcome: {
      executor_id: 'instanton.testnet',
      gas_burnt: 2428008201426,
      logs: [],
      metadata: [Object],
      receipt_ids: [Array],
      status: [Object],
      tokens_burnt: '242800820142600000000'
    },
    proof: [ [Object], [Object], [Object] ]
  }
}
```
@ailisp any ideas what this could be?

**Comment by ChaoticTempest** [comment]
Ahh, so I figured out why I was getting unreachable opcode. When deploying the contract bytes incorrectly or in the wrong encoding, it would result in this error. For example, the following diff makes a huge difference when reading in these bytes:
```diff
-   const bytes = readFileSync(base64File);
+   const bytes = readFileSync(base64File).toString();
    const base64Contract = Buffer.from(bytes, 'base64');
```
